/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsersRouteImport } from './routes/users'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReferralsRouteImport } from './routes/referrals'
import { Route as PharmacyRouteImport } from './routes/pharmacy'
import { Route as PatientsRouteImport } from './routes/patients'
import { Route as OpdQueueRouteImport } from './routes/opd-queue'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LaboratoryRouteImport } from './routes/laboratory'
import { Route as ClinicalRouteImport } from './routes/clinical'
import { Route as BillingRouteImport } from './routes/billing'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PatientsPatientIdRouteImport } from './routes/patients.$patientId'
import { Route as ClinicalPatientIdRouteImport } from './routes/clinical.$patientId'

const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferralsRoute = ReferralsRouteImport.update({
  id: '/referrals',
  path: '/referrals',
  getParentRoute: () => rootRouteImport,
} as any)
const PharmacyRoute = PharmacyRouteImport.update({
  id: '/pharmacy',
  path: '/pharmacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientsRoute = PatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => rootRouteImport,
} as any)
const OpdQueueRoute = OpdQueueRouteImport.update({
  id: '/opd-queue',
  path: '/opd-queue',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LaboratoryRoute = LaboratoryRouteImport.update({
  id: '/laboratory',
  path: '/laboratory',
  getParentRoute: () => rootRouteImport,
} as any)
const ClinicalRoute = ClinicalRouteImport.update({
  id: '/clinical',
  path: '/clinical',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingRoute = BillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientsPatientIdRoute = PatientsPatientIdRouteImport.update({
  id: '/$patientId',
  path: '/$patientId',
  getParentRoute: () => PatientsRoute,
} as any)
const ClinicalPatientIdRoute = ClinicalPatientIdRouteImport.update({
  id: '/$patientId',
  path: '/$patientId',
  getParentRoute: () => ClinicalRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/billing': typeof BillingRoute
  '/clinical': typeof ClinicalRouteWithChildren
  '/laboratory': typeof LaboratoryRoute
  '/login': typeof LoginRoute
  '/opd-queue': typeof OpdQueueRoute
  '/patients': typeof PatientsRouteWithChildren
  '/pharmacy': typeof PharmacyRoute
  '/referrals': typeof ReferralsRoute
  '/settings': typeof SettingsRoute
  '/users': typeof UsersRoute
  '/clinical/$patientId': typeof ClinicalPatientIdRoute
  '/patients/$patientId': typeof PatientsPatientIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/billing': typeof BillingRoute
  '/clinical': typeof ClinicalRouteWithChildren
  '/laboratory': typeof LaboratoryRoute
  '/login': typeof LoginRoute
  '/opd-queue': typeof OpdQueueRoute
  '/patients': typeof PatientsRouteWithChildren
  '/pharmacy': typeof PharmacyRoute
  '/referrals': typeof ReferralsRoute
  '/settings': typeof SettingsRoute
  '/users': typeof UsersRoute
  '/clinical/$patientId': typeof ClinicalPatientIdRoute
  '/patients/$patientId': typeof PatientsPatientIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/billing': typeof BillingRoute
  '/clinical': typeof ClinicalRouteWithChildren
  '/laboratory': typeof LaboratoryRoute
  '/login': typeof LoginRoute
  '/opd-queue': typeof OpdQueueRoute
  '/patients': typeof PatientsRouteWithChildren
  '/pharmacy': typeof PharmacyRoute
  '/referrals': typeof ReferralsRoute
  '/settings': typeof SettingsRoute
  '/users': typeof UsersRoute
  '/clinical/$patientId': typeof ClinicalPatientIdRoute
  '/patients/$patientId': typeof PatientsPatientIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/billing'
    | '/clinical'
    | '/laboratory'
    | '/login'
    | '/opd-queue'
    | '/patients'
    | '/pharmacy'
    | '/referrals'
    | '/settings'
    | '/users'
    | '/clinical/$patientId'
    | '/patients/$patientId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/billing'
    | '/clinical'
    | '/laboratory'
    | '/login'
    | '/opd-queue'
    | '/patients'
    | '/pharmacy'
    | '/referrals'
    | '/settings'
    | '/users'
    | '/clinical/$patientId'
    | '/patients/$patientId'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/billing'
    | '/clinical'
    | '/laboratory'
    | '/login'
    | '/opd-queue'
    | '/patients'
    | '/pharmacy'
    | '/referrals'
    | '/settings'
    | '/users'
    | '/clinical/$patientId'
    | '/patients/$patientId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  BillingRoute: typeof BillingRoute
  ClinicalRoute: typeof ClinicalRouteWithChildren
  LaboratoryRoute: typeof LaboratoryRoute
  LoginRoute: typeof LoginRoute
  OpdQueueRoute: typeof OpdQueueRoute
  PatientsRoute: typeof PatientsRouteWithChildren
  PharmacyRoute: typeof PharmacyRoute
  ReferralsRoute: typeof ReferralsRoute
  SettingsRoute: typeof SettingsRoute
  UsersRoute: typeof UsersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/referrals': {
      id: '/referrals'
      path: '/referrals'
      fullPath: '/referrals'
      preLoaderRoute: typeof ReferralsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pharmacy': {
      id: '/pharmacy'
      path: '/pharmacy'
      fullPath: '/pharmacy'
      preLoaderRoute: typeof PharmacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patients': {
      id: '/patients'
      path: '/patients'
      fullPath: '/patients'
      preLoaderRoute: typeof PatientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opd-queue': {
      id: '/opd-queue'
      path: '/opd-queue'
      fullPath: '/opd-queue'
      preLoaderRoute: typeof OpdQueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/laboratory': {
      id: '/laboratory'
      path: '/laboratory'
      fullPath: '/laboratory'
      preLoaderRoute: typeof LaboratoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clinical': {
      id: '/clinical'
      path: '/clinical'
      fullPath: '/clinical'
      preLoaderRoute: typeof ClinicalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing': {
      id: '/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof BillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clinical/$patientId': {
      id: '/clinical/$patientId'
      path: '/$patientId'
      fullPath: '/clinical/$patientId'
      preLoaderRoute: typeof ClinicalPatientIdRouteImport
      parentRoute: typeof ClinicalRoute
    }
    '/patients/$patientId': {
      id: '/patients/$patientId'
      path: '/$patientId'
      fullPath: '/patients/$patientId'
      preLoaderRoute: typeof PatientsPatientIdRouteImport
      parentRoute: typeof PatientsRoute
    }
  }
}

interface ClinicalRouteChildren {
  ClinicalPatientIdRoute: typeof ClinicalPatientIdRoute
}

const ClinicalRouteChildren: ClinicalRouteChildren = {
  ClinicalPatientIdRoute: ClinicalPatientIdRoute,
}

const ClinicalRouteWithChildren = ClinicalRoute._addFileChildren(
  ClinicalRouteChildren,
)

interface PatientsRouteChildren {
  PatientsPatientIdRoute: typeof PatientsPatientIdRoute
}

const PatientsRouteChildren: PatientsRouteChildren = {
  PatientsPatientIdRoute: PatientsPatientIdRoute,
}

const PatientsRouteWithChildren = PatientsRoute._addFileChildren(
  PatientsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  BillingRoute: BillingRoute,
  ClinicalRoute: ClinicalRouteWithChildren,
  LaboratoryRoute: LaboratoryRoute,
  LoginRoute: LoginRoute,
  OpdQueueRoute: OpdQueueRoute,
  PatientsRoute: PatientsRouteWithChildren,
  PharmacyRoute: PharmacyRoute,
  ReferralsRoute: ReferralsRoute,
  SettingsRoute: SettingsRoute,
  UsersRoute: UsersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
